points:
  key:
    padding: cx
  zones:
    matrix:
      anchor:
        rotate: 25
      columns:
        pinky:
          rows:
            top:
              shift: [-1.4, 0.5]
              rotate: 8
              bind: [0,16,4,0]
            home:
              bind: [4,16,4,0]
            bottom:
              shift: [-0.75, 0]
              rotate: -4
              bind: [4,0,0,0]
        ring:
          rotate: -9
          origin: [-12, -8]
          stagger: 10
          rows:
            top:
              shift: [-0.6, 1.2]
              rotate: 3
              bind: [0,16,4,0]
            home:
              bind: [4,4,4,4]
            bottom:
              shift: [-0.3, -1]
              rotate: -2
              bind: [4,12,0,4]
        middle:
          rotate: -3
          origin: [-0, -10]
          stagger: 4
          rows:
            top:
              shift: [0.0, 2.0]
              bind: [0,0,4,0]
            home:
              bind: [4,4,4,4]
            bottom:
              shift: [0.0, -2.0]
              bind: [4,4,0,4]
        index:
          rotate: -3
          origin: [-0, -4]
          stagger: -4
          rows:
            top:
              shift: [0.6, 1.2]
              rotate: -3
              bind: [0,0,4,8]
            home:
              bind: [4,0,4,4]
            bottom:
              shift: [0.3, -1]
              rotate: 2
              bind: [0,0,4,0]
      rows:
        bottom:
        home:
        top:
    thumbfan:
      anchor:
        ref: matrix_index_bottom
        shift: [-12, -20]
      columns:
        near:
          rotate: 3
          rows:
            thumb:
              bind: [8,4,0,0]
        home:
          spread: 20
          rotate: -15
          origin: [-10, -4]
          rows:
            thumb:
              bind: [0,2,0,4]
        far:
          spread: 20
          rotate: -15
          origin: [-10, -4]
          rows:
            thumb:
              bind: [0,0,0,24]
      rows:
        thumb:
  rotate: -20
  mirror:
    ref: matrix_pinky_home
    distance: 220
outlines:
  exports:
    raw: 
      - type: keys
        side: left
        size: [1cx - 0.5 , 1cx -0.5]
    cutout:
      - type: outline
        name: raw
        fillet: 2
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5]
        bound: false    
        tags: [1u]       
    keycap_outlines15:
      - type: keys
        side: left
        size: [1.5cx - 0.5, 1cy - 0.5]
        bound: false    
        tags: [15u]       
    preview:
        [keycap_outlines,keycap_outlines15]